In [52]:
import numpy as np

def gauss_elimination(A, y):
    A = A.astype(float)
    y = y.astype(float)
    n = A.shape[0]
    aug_matrix = np.concatenate((A, y.reshape(n, 1)), axis=1)

    # Convert to upper triangular form
    for i in range(n):
        # If diagonal element is zero, swap with a row below that has a non-zero in the same column
        if aug_matrix[i, i] == 0:
            for swap_i in range(i+1, n):
                if aug_matrix[swap_i, i] != 0:
                    aug_matrix[[i, swap_i]] = aug_matrix[[swap_i, i]]
                    break
            else:
                print("Matrix is singular.")
                return
                
        for j in range(i+1, n):
            ratio = aug_matrix[j, i] / aug_matrix[i, i]
            for k in range(n+1):
                aug_matrix[j, k] = aug_matrix[j, k] - ratio * aug_matrix[i, k]

    print("upper triangular matrix:")
    print(np.round(aug_matrix, 3))

    # Back-substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = aug_matrix[i, n] / aug_matrix[i, i]
        for j in range(i):
            aug_matrix[j, n] -= aug_matrix[j, i] * x[i]

    print("x:")
    print(np.round(x, 3))

In [53]:
# Sample 1
a = np.array([[1, 2, 3], [3, 4, 5], [3, 5, 5]])
y = np.array([2, 2, 5])
print("Sample 1:")
gauss_elimination(a, y)

# Sample 2
a = np.array([[1, 2, 3, 4], [5, 4, 3, 2], [2, 1, 2, 4], [2, 1, 3, 4]])
y = np.array([4, 8, 5, 6])
print("\nSample 2:")
gauss_elimination(a, y)

# Sample 3
a = np.array([[0, 0, 0], [3, 4, 5], [3, 5, 5]])
y = np.array([2, 2, 5])
print("\nSample 3:")
gauss_elimination(a, y)
print()


Sample 1:
upper triangular matrix:
[[ 1.  2.  3.  2.]
 [ 0. -2. -4. -4.]
 [ 0.  0. -2.  1.]]
x:
[-2.5  3.  -0.5]

Sample 2:
upper triangular matrix:
[[  1.    2.    3.    4.    4. ]
 [  0.   -6.  -12.  -18.  -12. ]
 [  0.    0.    2.    5.    3. ]
 [  0.    0.    0.   -2.5  -0.5]]
x:
[ 1.4 -0.6  1.   0.2]

Sample 3:
Matrix is singular.

