In [2]:
# Problem 1.2

import numpy as np

In [3]:
row_vector = np.array([[1,3,5,7,9]])

In [4]:
col_vector = np.array([[1],[2],[3],[4]])

In [5]:
temp = [[1,3,5,7,9]]

In [6]:
print(temp)

[[1, 3, 5, 7, 9]]


In [7]:
print(row_vector.shape)

(1, 5)


In [8]:
print(col_vector.shape)

(4, 1)


In [9]:
#Problem 1.3
from numpy.linalg import norm

row_trans = row_vector.T
#compute L1 norm for row_transpose
L1_norm = norm(row_trans,1)
#compute L2 norm for row_transpose
L2_norm = norm(row_trans,2)
#compute L_inf norm for row_transpose
L_inf_norm = norm(row_trans,np.inf)
print("L1 is : %.2f"%L1_norm)
print("L2 is : %.3f"%L2_norm)
print("L_inf : %.2f"%L_inf_norm)

L1 is : 25.00
L2 is : 12.845
L_inf : 9.00


In [10]:
#Problem 1.5
from numpy import arccos, dot #funciton for inverse cosine and dot product
v = np.array([[10,9,3]]) #vector v = [10, 9 ,3]T
w = np.array([[2,5,12]]) #vector w = [2, 5, 12]T

In [11]:
theta = arccos(dot(v,w.T)/(norm(v)*norm(w)))

In [12]:
print("theta is :%.2f"%theta)

theta is :0.98


C:\Users\User\AppData\Local\Temp\ipykernel_12428\2012805614.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("theta is :%.2f"%theta)


In [13]:
#problem 1.6
from numpy import cross
u = np.array([[0,2,0]])
t = np.array([[3,0,0]])
print(cross(u,t))

[[ 0  0 -6]]


In [14]:
#Problem 1.10
from numpy.linalg import inv
M = np.array([[0,2,1,3],
             [3,2,8,1],
             [1,0,0,3],
             [0,3,2,1]])

In [15]:
print(M)

[[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]


In [16]:
from numpy.linalg import det
print(det(M))

-38.000000000000014


In [17]:
print(inv(M)) #find inverse matrix

[[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]


In [18]:
#Problem 1.19
from numpy.linalg import solve
A = np.array([[4,3,-5],
              [-2,-4,5],
              [8,8,0]])
y = np.array([2,5,-3])
x = solve(A,y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [19]:
from numpy.linalg import inv
x = np.dot(inv(A),y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [20]:
from scipy.linalg import lu
P,L,U = lu(A)
print(L)
print(U)
print(P)

[[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
[[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [23]:
print(np.dot(L,U))

[[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]
