In [1]:
import numpy as np

In [2]:
def gauss_elimination(a,y):
    m=np.insert(a,len(a),y, axis=1)
    m=m.astype(float) 
    for i in range(len(a)):
        for j in range(i+1,len(a)):
            m[j]=m[j]-m[j][i]/m[i][i]*m[i]
    print('upper triangular matrix:')
    print(m)
    print()
    x=np.zeros(len(a))
    for i in range(len(a)-1,-1,-1):
        x[i]=m[i][len(a)]/m[i][i]
        for j in range(0,i):
            m[j][len(a)]=m[j][len(a)]-m[j][i]*x[i]
            m[j][i]=0
    print('x:') 
    print(np.array2string(x,separator=','))

In [3]:
a = np.array([[1, 2, 3],[3, 4, 5],[3, 5, 5]])
y = np.array([2, 2, 5])
gauss_elimination(a,y)

upper triangular matrix:
[[ 1.  2.  3.  2.]
 [ 0. -2. -4. -4.]
 [ 0.  0. -2.  1.]]

x:
[-2.5, 3. ,-0.5]


In [4]:
a = np.array([[1, 2, 3, 4],[5, 4, 3, 2],[2, 1, 2, 4],[2, 1, 3, 4]])
y = np.array([4, 8, 5, 6])
gauss_elimination(a,y)

upper triangular matrix:
[[  1.    2.    3.    4.    4. ]
 [  0.   -6.  -12.  -18.  -12. ]
 [  0.    0.    2.    5.    3. ]
 [  0.    0.    0.   -2.5  -0.5]]

x:
[ 1.4,-0.6, 1. , 0.2]
