In [20]:
import numpy as np

In [21]:
def gauss_jordan_elimination(a, y):
    m = np.insert(a, len(a), y, axis=1)
    m = m.astype(float)

    # 上三角矩陣
    for i in range(len(a)):
        for j in range(i+1, len(a)):
            m[j] = m[j] - m[j][i] / m[i][i] * m[i]

    # 將對角線元素變成1
    for i in range(0, len(a)):
        m[i] = m[i] / m[i][i]

    # 讓矩陣剩下對角線元素
    for i in range(len(a)-1, -1, -1):
        for j in range(i-1, -1, -1):
            m[j] = m[j] - m[j][i] / m[i][i] * m[i]

    print('diagonal matrix:')
    print(m)
    print()

    x = np.zeros(len(a))
    for i in range(len(a)):
        x[i] = m[i][len(a)]

    print('x:')
    print(np.array2string(x, separator=','))

In [22]:
a = np.array([[1, 2, 3],[3, 4, 5],[3, 5, 5]])
y = np.array([2, 2, 5])
gauss_jordan_elimination(a,y)

diagonal matrix:
[[ 1.   0.   0.  -2.5]
 [ 0.   1.   0.   3. ]
 [-0.  -0.   1.  -0.5]]

x:
[-2.5, 3. ,-0.5]


In [23]:
a = np.array([[1, 2, 3, 4],[5, 4, 3, 2],[2, 1, 2, 4],[2, 1, 3, 4]])
y = np.array([4, 8, 5, 6])
gauss_jordan_elimination(a,y)

diagonal matrix:
[[ 1.   0.   0.   0.   1.4]
 [ 0.   1.   0.   0.  -0.6]
 [ 0.   0.   1.   0.   1. ]
 [-0.  -0.  -0.   1.   0.2]]

x:
[ 1.4,-0.6, 1. , 0.2]
