In [13]:
import numpy as np
from numpy.linalg import det

In [14]:
def LU_decomposition(a, y):
    a = a.astype('float')
    y = y.astype('float')
    m = np.insert(a, len(a), y, axis=1)  # 增廣矩陣
    L = np.zeros((len(a), len(a)))

    # 求上三角矩陣
    for i in range(len(a) - 1):
        for j in range(len(a) - 1 - i):
            x = m[i][i] / m[i + 1 + j][i]
            L[i + 1 + j][i] = 1 / x  # x的值放入L矩陣
            for k in range(len(m[0])):
                m[i + j + 1][k] = m[i + j + 1][k] - m[i][k] / x  # 將左下角元素減為0
                m[i + j + 1][k] = m[i + j + 1][k].astype('float')

    U = np.delete(m, len(m[0]) - 1, 1)  # 將增廣矩陣最後的column刪除

    # 將L矩陣對角線設為1
    for i in range(len(L)):
        L[i][i] = 1

    print("u_matrix:")
    print(U)
    print("l_matrix:")
    print(L)

    return (L, U)


def dot_array(A, y):  # A的反矩陣乘y
    adj_A = np.zeros((len(A), len(A)))

    for i in range(len(A)):
        for j in range(len(A)):
            a = np.delete(A, [i], axis=0)
            a = np.delete(a, [j], axis=1)
            adj_A[i][j] = np.linalg.det(a) * (-1) ** (i + j)

    adj_A = np.transpose(adj_A)
    A = A.astype('float')
    y = y.astype('float')
    det_A = np.linalg.det(A)
    inverse_matrix = adj_A / det_A
    answer = np.dot(inverse_matrix, y.T)

    return answer


def gauss_elimination(a, y):
    m = np.insert(a, len(a), y, axis=1)
    m = m.astype(float)
    x = np.zeros(len(a))

    for i in range(len(a)):
        for j in range(i + 1, len(a)):
            m[j] = m[j] - m[j][i] / m[i][i] * m[i]

    for i in range(len(a) - 1, -1, -1):
        x[i] = m[i][len(a)] / m[i][i]
        for j in range(0, i):
            m[j][len(a)] = m[j][len(a)] - m[j][i] * x[i]
            m[j][i] = 0

    return x

def main(a,y):
    L,U=LU_decomposition(a,y)#求L、U
    L_inverse_y=dot_array(L,y)#(L**-1)y 
    ans=gauss_elimination(U,L_inverse_y)#高斯消去法
    print("x:")
    print(ans)


In [15]:
a = np.array([[1, 2, 3],[3, 4, 5],[3, 5, 5]])
y = np.array([2, 2, 5])
main(a,y)

u_matrix:
[[ 1.  2.  3.]
 [ 0. -2. -4.]
 [ 0.  0. -2.]]
l_matrix:
[[1.  0.  0. ]
 [3.  1.  0. ]
 [3.  0.5 1. ]]
x:
[-2.5  3.  -0.5]


In [16]:
a = np.array([[1, 2, 3, 4],[5, 4, 3, 2],[2, 1, 2, 4],[2, 1, 3, 4]])
y = np.array([4, 8, 5, 6])
main(a,y)

u_matrix:
[[  1.    2.    3.    4. ]
 [  0.   -6.  -12.  -18. ]
 [  0.    0.    2.    5. ]
 [  0.    0.    0.   -2.5]]
l_matrix:
[[1.  0.  0.  0. ]
 [5.  1.  0.  0. ]
 [2.  0.5 1.  0. ]
 [2.  0.5 1.5 1. ]]
x:
[ 1.4 -0.6  1.   0.2]
